var annotated_dup =
[
    [ "vego", null, [
      [ "GameRegistryHelper", "classvego_1_1GameRegistryHelper.html", null ]
    ] ],
    [ "Animation", "structAnimation.html", null ],
    [ "ColliderComponent", "classColliderComponent.html", null ],
    [ "CollisionHandler", "classCollisionHandler.html", "classCollisionHandler" ],
    [ "Component", "classComponent.html", null ],
    [ "ConfigLoader", "classConfigLoader.html", null ],
    [ "DataComponent", "classDataComponent.html", "classDataComponent" ],
    [ "Entity", "classEntity.html", "classEntity" ],
    [ "EventManager", "classEventManager.html", "classEventManager" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "GameFactory", "classGameFactory.html", null ],
    [ "GameInternal", "classGameInternal.html", null ],
    [ "HealthComponent", "classHealthComponent.html", null ],
    [ "InputComponent", "classInputComponent.html", null ],
    [ "InputManager", "classInputManager.html", "classInputManager" ],
    [ "InteractionComponent", "classInteractionComponent.html", "classInteractionComponent" ],
    [ "InteractionEventdataStruct", "structInteractionEventdataStruct.html", "structInteractionEventdataStruct" ],
    [ "InteractionListener", "classInteractionListener.html", null ],
    [ "InteractionManager", "classInteractionManager.html", null ],
    [ "Manager", "classManager.html", "classManager" ],
    [ "Map", "classMap.html", "classMap" ],
    [ "PickupComponent", "classPickupComponent.html", "classPickupComponent" ],
    [ "PickupManager", "classPickupManager.html", null ],
    [ "PlayerComponent", "classPlayerComponent.html", null ],
    [ "ProjectileComponent", "classProjectileComponent.html", null ],
    [ "RenderManager", "classRenderManager.html", "classRenderManager" ],
    [ "RenderObject", "classRenderObject.html", "classRenderObject" ],
    [ "SoundManager", "classSoundManager.html", null ],
    [ "SpriteComponent", "classSpriteComponent.html", null ],
    [ "StatEffect", "structStatEffect.html", "structStatEffect" ],
    [ "StatEffectsComponent", "classStatEffectsComponent.html", "classStatEffectsComponent" ],
    [ "TextureManager", "classTextureManager.html", "classTextureManager" ],
    [ "Textures", "classTextures.html", null ],
    [ "TileComponent", "classTileComponent.html", null ],
    [ "TransformComponent", "classTransformComponent.html", "classTransformComponent" ],
    [ "Vector2D", "classVector2D.html", null ]
];